// Common key codes for Karabiner-Elements
export const COMMON_KEYS = [
  'a',
  'b',
  'c',
  'd',
  'e',
  'f',
  'g',
  'h',
  'i',
  'j',
  'k',
  'l',
  'm',
  'n',
  'o',
  'p',
  'q',
  'r',
  's',
  't',
  'u',
  'v',
  'w',
  'x',
  'y',
  'z',
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  '0',
  'return_or_enter',
  'escape',
  'delete_or_backspace',
  'tab',
  'spacebar',
  'hyphen',
  'equal_sign',
  'open_bracket',
  'close_bracket',
  'backslash',
  'semicolon',
  'quote',
  'grave_accent_and_tilde',
  'comma',
  'period',
  'slash',
  'caps_lock',
  'f1',
  'f2',
  'f3',
  'f4',
  'f5',
  'f6',
  'f7',
  'f8',
  'f9',
  'f10',
  'f11',
  'f12',
  'f13',
  'f14',
  'f15',
  'f16',
  'f17',
  'f18',
  'f19',
  'f20',
  'left_shift',
  'right_shift',
  'left_control',
  'right_control',
  'left_option',
  'right_option',
  'left_command',
  'right_command',
  'up_arrow',
  'down_arrow',
  'left_arrow',
  'right_arrow',
  'page_up',
  'page_down',
  'home',
  'end',
  'insert',
  'delete_forward',
  'fn',
  'help',
  'mute',
  'volume_decrement',
  'volume_increment',
] as const;

// Available modifiers in Karabiner-Elements
export const MODIFIERS = [
  'left_command',
  'right_command',
  'command',
  'left_control',
  'right_control',
  'control',
  'left_option',
  'right_option',
  'option',
  'left_shift',
  'right_shift',
  'shift',
  'caps_lock',
  'fn',
  'any',
] as const;

// Condition types supported by Karabiner-Elements
export const CONDITION_TYPES = [
  'frontmost_application_if',
  'frontmost_application_unless',
  'device_if',
  'device_unless',
  'keyboard_type_if',
  'keyboard_type_unless',
  'input_source_if',
  'input_source_unless',
  'variable_if',
  'variable_unless',
  'event_changed_if',
  'event_changed_unless',
] as const;

// To event types supported by Karabiner-Elements
export const TO_EVENT_TYPES = [
  'key_code',
  'shell_command',
  'set_variable',
  'select_input_source',
  'mouse_key',
] as const;

// Keyboard types for conditions
export const KEYBOARD_TYPES = ['ansi', 'iso', 'jis'] as const;
